### ISSUE TITLE
23.01.27 할 일들... <3 <3 <333....

### ISSUE THREAD

**Issue by ittzggd** [Yes-l-CAN/YesYOUCAN#2]
### ISSUE
 * Type: `feature`
 
### 🐧TODO (구조)
- [x]  재조립 구현
- [ ]  함수 정리 (필요없는거 쳐내고 안 쓰는거 쳐내고 void 없애고 겹치는거 합치고 등등..)
- [x]  파일보내기
- [ ]  signal 처리 -> serverEnd 함수 구현 (delete, 소멸자 호출 플로우 정리)

 ### 🐧TODO (명령어)
- [x] KICK) 방장이 아닌 경우 : Irssi: critical nicklist_set_host: assertion   'host != NULL' failed 해결
- [x] KICK) 방장인 경우: 에러 출력됨
- [x] 'Welcome!' 메세지 뜨기 전 아무런 출력물도 출력되면 안됨
- [x] (Irssi format) USER가 세팅된 상태에서 USER 명령어를 사용하려 할 때 에러메세지 출력해야 함 => 고려하지 않아도 됨!! USERHOST로 바꿔서 들어가게 되기 때문!
- [x] 아무것도 안한 상태에서 KICK하면 abort / 그냥 KICK도 abort...😇
- [x] PART 시에 채널에 그대로 남아있음
- [x] NICK 변경시에  적용 안 됨 -> 아마 아래 문제도 같은 원인일 듯 
- [x] client1 에서 hihi -> hey 로 NICK을 바꿨는데, client2에서 hihi 로 닉네임을 쓰고 싶을 때 (433 5 hihi :Nickname is already in use) 에러가 발생
- [x] JOIN hi 하면 중복으로 JOIN hi 가 다시 출력됨!
- [x] PRIVMSG 사용자 지정 했을 때 포멧 에러 (400 hihi PRIVMSG :Invalid Format error !)
- [x] PRIVMSG 사용자 지정하지 않고 채널만 포함했을 때 포멧 에러 (400 hihi PRIVMSG :Invalid Format error !)

 ### 🐧TODO (파싱)
- [x] 파싱에서 \r\n 이 있는지 검사하기보다 \r || \n 을 검사해서 둘중 하나만 있으면 파싱/ 데이터 나누기
- [x] (위의 내용에 추가하여) Ping.cpp 71줄에서 length에서 -2를 빼는데 위의 기준대로 고친다면, 이또한 -1만 빼야함!

 ### 🐧TODO (출력)
- [x] 뉴메릭 포맷 맞춰서 에러 메세지들 수정
- [x] 서버 접속하고 USSER처럼 잘못 입력하면 그냥 무한루프 돎.. <- 에러메세지 필요해보임!!

 ### 🐧TODO (서비스)
- [ ] format error 가 발생할 때, 뒷쪽에 해당 명령어의 포맷 추가
- [ ] 시스템에서 띄워주는 것들을 컬러로 표시

**Comment by nimo-my** [comment]
CanClient::addSendBuff 해주고 해당 함수 안에 buffer.clear()까지 넣어주면 안되려나용?
